version: "3"
services:
  db:
    image: mysql
    volumes:
      - db-data:/var/lib/mysql
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_DATABASE:  'ecole' 
    networks:
      - dev

  phpmyadmin:
    image: phpmyadmin
    depends_on:
      - db
    ports:
      - 8090:80
    environment:
      PMA_HOST: db
    networks:
      - dev

networks:
  dev:

volumes:
  db-data:
